apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sync-windows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/argo-appprojects-test
    path: components/argo-cd-sync-windows
    helm:
      version: v3
      values: |
        sleepConfigs: {{- toYaml .Values.clusterSleep.configs | nindent 10}}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true