apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: kube-green
  source:
    repoURL: https://github.com/paoloyx/argo-appprojects-test
    path: components/nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true