apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-green
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  syncWindows:
   - kind: deny
     schedule: 30 09 * * 1-5
     duration: 1h
     namespaces:
       - kube-system
