apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml
  - bitbucket-credentials-template.yaml
  - argocd-notifications-secret.yaml
patchesStrategicMerge:
  - argocd-resources-patch.yaml
  - argocd-cm-patch.yaml
  - argocd-notifications-secret-patch.yaml
  - argocd-notifications-resources-patch.yaml
  - argocd-notifications-cm-patch.yaml