{{- range $sleepName, $sleepValues := .Values.sleepConfigs }}
{{- if $sleepValues.enabled }}
{{- range $namespace := $sleepValues.namespaces }}
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: {{ $sleepName}}
  namespace: {{ $namespace}}
spec:
  weekdays: {{ $sleepValues.weekdays | quote }}
  sleepAt: {{ $sleepValues.sleepAt | quote  }}
  wakeUpAt: {{ $sleepValues.wakeUpAt | quote }}
  timeZone: {{ $sleepValues.timeZone | default "Europe/Rome" | quote }}
  suspendCronJobs: false
---
{{- end }}
{{- end }}
{{- end }}