{{- range $sleepName, $sleepValues := .Values.sleepConfigs }}
  {{- $sleepEnabled := $sleepValues.enabled | default false }}
  {{- if $sleepEnabled }}
    {{- range $namespace := $sleepValues.namespaces }}
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: {{ $sleepName}}
  namespace: {{ $namespace}}
spec:
  weekdays: {{ $sleepValues.weekdays | quote }}
  sleepAt: {{ $sleepValues.sleepAt | quote  }}
  timeZone: {{ $sleepValues.timeZone | default "Europe/Rome" | quote }}
  suspendCronJobs: {{ $sleepValues.suspendCronJobs | default false }}
---
    {{- end }}
  {{- end }}
{{- end }}