apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-green-sleep-configurations
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/argo-appprojects-test
    path: components/kube-green/sleep-configurations
    helm:
      version: v3
      values: |
        sleepConfigs: {{- toYaml .Values.sleepConfigs | nindent 10}}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true