apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-green
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  syncWindows:
{{- range $sleepValues := .Values.sleepConfigs }}
{{- if $sleepValues.enabled }}
{{- $sleepAt := mustToDate "15:04" $sleepValues.sleepAt | date_modify "1m" | date "15:04" }}
{{- $schedule := printf "%s %s * * %s" (substr 3 5 $sleepAt) (substr 0 2 $sleepAt) $sleepValues.weekdays }}
  - kind: deny
    schedule: {{ $schedule | quote }}
    duration: {{ $sleepValues.duration | quote }}
    timeZone: {{ $sleepValues.timeZone | default "Europe/Rome" | quote }}
    {{- with $sleepValues.namespaces }}
    namespaces:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}